name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/Perpustakaan/Perpustakaan
            git pull origin main
            npm install --production
            cd frontend
            npm install
            npm run build
            mkdir -p /var/www/ucup-edu-lib/frontend/dist
            cp -r dist/. /var/www/ucup-edu-lib/frontend/dist/
            cd ..
            pm2 restart perpustakaan-api

